name: piratepx

services:
  postgres:
    image: postgres:16-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: piratepx_development
      POSTGRES_PASSWORD: password
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
